### ISSUE TITLE
cannot install search engines from Mycroft

### ISSUE THREAD

**Issue by eadmaster** [MrAlex94/Waterfox-Old#126]
https://mycroftproject.com/

I've also tried with this userscript:
https://greasyfork.org/en/scripts/405759-mycroft-patch-for-firefox-78

**Comment by buttercookie42** [comment]
I think the only caveat is that you need to have the separate search bar visible because it seems that Classic doesn't implement adding search engines from the main location bar. Other than it seems to be working perfectly fine for me, without the aid of any userscripts. (If anything, you'd want a reverse user script that restores the old way of adding a search engine via the old `Window.sidebar.addSearchEngine`-API that I think was removed in Firefox 59? Mycroft moved to this new model of search engine installation that remains compatible with current Firefoxes quite a while ago.)

**Comment by michael-j-oconnor** [comment]
I can confirm that installing search engines in Waterfox Classic 2022.04 works just fine with the separate search bar.
