### ISSUE TITLE
no current compile for macOS and Windows (for now or anymore)?

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox-Old#22]
https://github.com/WaterfoxCo/Waterfox-Classic/releases/tag/2021.11-classic

I hope it's not a general decision but just current lack of time to do a decent compile for Mac and Windows? Just curious.

Above all, thanks for all your magnificent work 👍 !!

**Comment by hawkeye116477** [comment]
As you can see, there is also missing build for Windows and no proper changelog.

It's because action run https://github.com/WaterfoxCo/Waterfox-Classic/actions/runs/1491211087 failed and still not fixed by MrAlex94. Well as I see, he now fully focuses on G4 and lacks time for Classic. 
Let's compare security updates release time with Pale Moon, formerly updates for Classic were much faster, now it's even more than 1 week delay after Pale Moon release.

**Comment by LeeBinder** [comment]
ah OK, gotcha. I totally didn't even have Windows on my radar at all (why runs Windows when there are doors LOL). 

I totally understand. Good luck finding the blockage!

**Comment by LeeBinder** [comment]
Ha, macOS won the race with Windows as usual :) 👍 

![Bildschirmfoto 2021-11-25 um 18 52 47](https://user-images.githubusercontent.com/39203497/143485281-329b1572-a513-4952-801e-114fd58fb96b.jpg)

**Comment by MrAlex94** [comment]
Ach, just as the workflow is fixed..the Linux runner had a connection error uploading the Linux tarball 🤦‍♂️

Will try get that uploaded tomorrow.

Anyway, will close this now :-)

**Comment by LeeBinder** [comment]
ya well, you've deserved a good nite's sleep 🥇

**Comment by mindwarp42** [comment]
Should/will there be corresponding incremental updates and/or a new full portable build for Windows? The .mar files are there for MacOS and Linux, but not for Windows. Using the full installer is fine if you use the non-portable Windows version, of course.
